### ISSUE TITLE
Add support for interoperability

### ISSUE THREAD

**Issue by clemherreman** [mrkrstphr/array-config#4]
Hello,

First, thank you a lot for your work! I'd like to use some configuration in a mrkrstphr/array-config from another tool in my platform, that is written in python. It's an application that monitors my PHP daemons _(which are using mrkrstphr/array-config files)_ and triggers our 24/7 on-call support.

Do you have a roadmap for supporting such cases, as there is no valid reasons not to use PHP arrays as config?

**Comment by bweston92** [comment]
I like the pun however, use a distributed configuration. Use something like Etcd and have the configuration updated in both places by something like Confd.

**Comment by mrkrstphr** [comment]
Duplicate of #1, closing, wontfix, yolo.
